# Generated by Django 4.1.6 on 2023-02-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect", models.CharField(max_length=100)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("POS", "POS"), ("NEG", "NEG"), ("NEU", "NEU")],
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("tags", models.ManyToManyField(blank=True, to="training.tag")),
            ],
        ),
    ]
